services:
  # Backend
  - type: web
    name: salm-backend
    runtime: python
    repo: https://github.com/premnandha1805/salm
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: salm-db
          property: connectionString

  # Frontend
  - type: web
    name: salm-frontend
    runtime: node
    repo: https://github.com/premnandha1805/salm
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: salm-backend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: salm-db
    databaseName: leave_db
    user: salm_user

version: "1"
